//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SupermarketConsoleApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderItem
    {
        public int OrdItemNo { get; set; }
        public string ItemId { get; set; }
        public int Price { get; set; }
        public int OrderNo { get; set; }
    
        public virtual Order Order { get; set; }
        public virtual Product Product { get; set; }
    }
}
