//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SupermarketConsoleApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Promotion
    {
        public int Id { get; set; }
        public int TypeId { get; set; }
        public string ProductCode { get; set; }
        public Nullable<int> RequiredQuantity { get; set; }
        public Nullable<int> QuantityDiscount { get; set; }
        public Nullable<int> SalePercent { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual PromotionType PromotionType { get; set; }
    }
}
